version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ALGO=HS256
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
